xcodebuild_arguments: 
    - "-project"
    - "Overdrive/Overdrive.xcodeproj"
    - "-scheme"
    - "Overdrive iOS"
custom_categories: 
  - 
    name: "Classes"
    children: 
      - "Task"
      - "InlineTask"
      - "TaskQueue"
  -
    name: "Protocols"
    children:
      - "TaskObserver"
      - "TaskCondition"
      - "TaskQueueDelegate"
  -
    name: "Enums"
    children:
      - "Result"
      - "TaskConditionResult"
      - "TaskConditionError"
  -
    name: "Extensions"
    children:
      - "CollectionType"
      - "NSOperation"
      - "NSQualityOfService"
