---
xcodebuild_arguments:
  - "-project"
  - Overdrive/Overdrive.xcodeproj
  - "-scheme"
  - Overdrive
custom_categories:
  -
    name: "Intro"
    children:
      - "Getting Started"
      - "Installation"
      - "State Machine"
  -
    name: "Classes"
    children:
      - "Task"
      - "TaskQueue"
      - "InlineTask"
      - "TaskBase"
  -
    name: "Protocols"
    children:
      - "TaskObserver"
      - "TaskCondition"
      - "TaskQueueDelegate"
  -
    name: "Enums"
    children:
      - "Result"
      - "TaskConditionResult"
      - "TaskConditionError"
  -
    name: "More information"
    children:
      - "License"
