language: objective-c
osx_image: xcode8
branches:
  only:
  - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
  - COMMAND="test-ios"
  - COMMAND="test-macos"
  - COMMAND="test-tvos"
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- sh build.sh "$COMMAND"
